### ISSUE TITLE
Can this approach be used to calculate fractal dimension in a 2-dimensional space and on networks?

### ISSUE THREAD

**Issue by deemeetree** [ChatzigeorgiouGroup/FractalDimension#2]
What if we have a network represented as a 2-dimensional space - can we use this approach to calculate its fractal dimension? Thank you!

**Comment by DanielDondorp** [comment]
Hi deemeetree,

What kind of network are we talking about here? Do you have an example?

Daniel

**Comment by deemeetree** [comment]
Hey @DanielDondorp  - yes, it's a text network of co-occurrences between the words. i can export it in any possible way, if needed. By default it is in a javascript object with the nodes and edges.

**Comment by DanielDondorp** [comment]
In that case I think the fractal dimension might not be the best approach, since it is really more of an image analysis technique. In your case, in any visual representation of the graph the location of the nodes would be arbitrary. The FD would be largely determined by how you decide to draw the vertices meaning that depending on how you decide to draw the networks you could get a whole range of FD values. There are ways to describe graph complexity or network complexity in an quantitative way but I honestly don`t know very much about that.
